# Generated by Django 2.1.1 on 2018-09-08 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0002_order_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='twitter_password',
            field=models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='Twitter Password'),
        ),
    ]
