# Generated by Django 2.1.1 on 2018-09-12 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0004_order_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='hashtags',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True, verbose_name='Hashtags'),
        ),
        migrations.AddField(
            model_name='order',
            name='similar_users',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True, verbose_name='Similar Users'),
        ),
    ]
