# Generated by Django 2.1.1 on 2018-09-24 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0006_order_txn_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='twitter_username',
            field=models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='Twitter Username'),
        ),
    ]
